title: "Nirooba Blog"
email: nirooba98@gmail.com
timezone: EST
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/newlogo.png'
favicon: 'assets/images/favicon.ico'
author: Nirooba
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  Nirooba:
    name: Nirooba
    display_name:  Nirooba
    avatar: 'assets/images/sal.png'
    email: nirooba98@gmail.com
    web: https://nirooba.com
    description: ""
  Shivasurya:
    name: Shivasurya
    display_name: Shivasurya
    avatar: 'assets/images/john.png'
    email: s.shivasurya@gmail.com
    web: https://shivasurya.me
    twitter: https://twitter.com/sshivasurya
    description: ""

# Social
social:
  github: https://github.com/nirooba98
  linkedin: https://www.linkedin.com/in/pon-nirooba/
  website: https://nirooba.com/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives